version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch-days: 2
      semver-minor-days: 5
      semver-major-days: 14
    groups:
      patch-minor:
        update-types: ["patch", "minor"]
